from . import endpoint_contacts
from . import endpoint_partner_category
from . import endpoint_sale_order_canal
from . import endpoint_sale_order_tipo_entrega
from . import endpoint_sale_order_zona
from . import endpoint_crm_team
from . import endpoint_res_currency_rate
from . import endpoint_promotion_card
from . import endpoint_coeficiente_tarjetas
from . import endpoint_stock_warehouse
from . import endpoint_res_bank
from . import endpoint_account_tax
from . import endpoint_l10n_latam_document_type
from . import endpoint_stock_picking
from . import endpoint_account_journal
from . import endpoint_l10n_ar_afip_responsibility_type
from . import endpoint_sale_order
from . import endpoint_product_product
from . import endpoint_product_pricelist